FROM node:lts-alpine

WORKDIR '/app'

# Copt the package.json file for npm install
COPY ./package.json ./

RUN npm install

# Copy all the npm installed files over
COPY . .

CMD [ "npm", "run", "start" ]
