version: '3'

services:
  web:
    build: 
      context: .                  # Look in current working directory
      dockerfile: Dockerfile.dev  # For a dockerfile called dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules   # Mapping node_modules separately
      - .:/app              # Mapping pwd to /app inside container

  # Creating the second service for running test - see explanation file for why
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:app
    # overriding the default run command.
    command: ["npm", "run", "test"]